experiment:
    tokenizer_checkpoint: /path/to/tokenizer-checkpoint/ema_model/pytorch_model.bin
    generator_checkpoint: /path/to/generator-checkpoint/ema_model/pytorch_model.bin
    output_dir: "sftok-b"

model:
    vq_model:
        codebook_size: 8192
        token_size: 32
        use_l2_norm: True
        commitment_cost: 0.25
        # vit arch
        vit_enc_model_size: "base"
        vit_enc_patch_size: 16
        num_latent_tokens: 64
        num_group: 1
        finetune_decoder: True
        semantic_guide: null
        pretrained_tokenizer_weight: "maskgit-vqgan-imagenet-f16-256.bin"
    decoder:
        # sftok
        vit_dec_model_size: "base"
        vit_dec_patch_size: 16
        num_latent_tokens: 64
        token_size: 32
        num_proxy_codes: 256
        codebook_size: 1024
        finetune_decoder: False
        semantic_guide: null

        # sampling hyper-params on the flight
        randomize_temperature: 1.0 # 1.0
        guidance_scale: 0.0 # 4.5
        guidance_decay: "constant"

        embedding_width: 1024
        embedding_init: False

        replace_prob: 0.8
    
    img_generator:
        model_type: "ViT"
        hidden_size: 768
        num_hidden_layers: 24
        num_attention_heads: 16
        intermediate_size: 3072
        dropout: 0.1
        attn_drop: 0.1
        num_steps: 8
        class_label_dropout: 0.1
        image_seq_len: ${model.vq_model.num_latent_tokens}
        condition_num_classes: 1000
        randomize_temperature: 1.0
        guidance_scale: 4.5 # 3.0
        guidance_decay: "constant"

losses:
    label_smoothing: 0.1
    loss_weight_unmasked_token: 0.1

dataset:
    params:
        train_shards_path_or_url: /path/to/data/train
        eval_shards_path_or_url: /path/to/data/val
        num_workers_per_gpu: 12
        dataset_type: simple_image_dataset
    preprocessing:
        resize_shorter_edge: 256
        crop_size: 256
        random_crop: False
        random_flip: True

optimizer:
    name: adamw 
    params:
        learning_rate: 2e-4
        beta1: 0.9
        beta2: 0.96
        weight_decay: 0.03


lr_scheduler:
    scheduler: "cosine"
    params:
        learning_rate: ${optimizer.params.learning_rate}
        warmup_steps: 10_000
        end_lr: 1e-5


training:
    gradient_accumulation_steps: 1
    per_gpu_batch_size: 256 # 32 GPU, total batch size 2048
    mixed_precision: "bf16"
    enable_tf32: True
    enable_wandb: False
    use_ema: True
    seed: 42
    max_train_steps: 1_000_000
    max_grad_norm: 1.0